CREATE TABLE [DBO].[TB_USUARIO]
(
	[ID_USUARIO] INT NOT NULL PRIMARY KEY, 
	[LOGIN] NVARCHAR(20) NOT NULL, 
    [SENHA] NVARCHAR(8) NOT NULL, 
    [PAPEL] BIT NOT NULL, 
    [VALOR_MIN_VISTO_APROVACAO] NUMERIC NOT NULL, 
    [VALOR_MAX_VISTO_APROVACAO] NUMERIC NOT NULL
)


CREATE TABLE [dbo].[TB_HISTORICO_APROVACAO]
(
	[ID_APROVACAO] INT NOT NULL , 
    [ID_USUARIO] INT NOT NULL, 
    [OPERACAO] BIT NOT NULL, 
    PRIMARY KEY ([ID_APROVACAO])
)

CREATE TABLE [DBO].[TB_NOTA_COMPRA]
(
	[ID_NOTA_COMPRA] INT NOT NULL PRIMARY KEY, 
    [DATA_EMISSAO] DATETIME NOT NULL, 
    [VALOR_MERCADORIA] NUMERIC(18, 2) NOT NULL, 
    [VALOR_DESCONTO] NUMERIC(18, 2) NOT NULL, 
    [VALOR_FRETE] NUMERIC(18, 2) NULL, 
    [VALOR_TOTAL] NUMERIC(18, 2) NULL, 
    [STATUS] BIT NULL
)

