USE [Aprovacao]
GO
/****** Object:  Table [dbo].[TB_CONFIGURACAO]    Script Date: 26/02/2018 17:41:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_CONFIGURACAO](
	[ID_CONFIGURACAO] [int] IDENTITY(1,1) NOT NULL,
	[FAIXA_INICIAL] [numeric](18, 2) NOT NULL,
	[FAIXA_FINAL] [numeric](18, 2) NOT NULL,
	[VISTO] [int] NOT NULL,
	[APROVACAO] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_CONFIGURACAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[TB_HISTORICO_APROVACAO]    Script Date: 26/02/2018 17:41:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_HISTORICO_APROVACAO](
	[ID_HISTORICO_APROVACAO] [int] IDENTITY(1,1) NOT NULL,
	[ID_USUARIO] [int] NOT NULL,
	[ID_NOTA_COMPRA] [int] NOT NULL,
	[OPERACAO] [bit] NOT NULL,
	[DATA] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_HISTORICO_APROVACAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[TB_NOTA_COMPRA]    Script Date: 26/02/2018 17:41:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_NOTA_COMPRA](
	[ID_NOTA_COMPRA] [int] IDENTITY(1,1) NOT NULL,
	[DATA_EMISSAO] [datetime] NOT NULL,
	[VALOR_MERCADORIA] [numeric](18, 2) NOT NULL,
	[VALOR_DESCONTO] [numeric](18, 2) NOT NULL,
	[VALOR_FRETE] [numeric](18, 2) NULL,
	[VALOR_TOTAL] [numeric](18, 2) NULL,
	[STATUS] [smallint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_NOTA_COMPRA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[TB_USUARIO]    Script Date: 26/02/2018 17:41:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_USUARIO](
	[ID_USUARIO] [int] IDENTITY(1,1) NOT NULL,
	[LOGIN] [nvarchar](20) NOT NULL,
	[SENHA] [nvarchar](8) NOT NULL,
	[PAPEL] [smallint] NOT NULL,
	[VALOR_MIN_VISTO_APROVACAO] [numeric](18, 0) NOT NULL,
	[VALOR_MAX_VISTO_APROVACAO] [numeric](18, 0) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET IDENTITY_INSERT [dbo].[TB_CONFIGURACAO] ON 

INSERT [dbo].[TB_CONFIGURACAO] ([ID_CONFIGURACAO], [FAIXA_INICIAL], [FAIXA_FINAL], [VISTO], [APROVACAO]) VALUES (1, CAST(0.00 AS Numeric(18, 2)), CAST(1000.00 AS Numeric(18, 2)), 1, 0)
INSERT [dbo].[TB_CONFIGURACAO] ([ID_CONFIGURACAO], [FAIXA_INICIAL], [FAIXA_FINAL], [VISTO], [APROVACAO]) VALUES (2, CAST(1000.01 AS Numeric(18, 2)), CAST(10000.00 AS Numeric(18, 2)), 1, 1)
INSERT [dbo].[TB_CONFIGURACAO] ([ID_CONFIGURACAO], [FAIXA_INICIAL], [FAIXA_FINAL], [VISTO], [APROVACAO]) VALUES (3, CAST(10000.01 AS Numeric(18, 2)), CAST(50000.00 AS Numeric(18, 2)), 2, 1)
INSERT [dbo].[TB_CONFIGURACAO] ([ID_CONFIGURACAO], [FAIXA_INICIAL], [FAIXA_FINAL], [VISTO], [APROVACAO]) VALUES (4, CAST(50000.01 AS Numeric(18, 2)), CAST(999999.99 AS Numeric(18, 2)), 2, 1)
SET IDENTITY_INSERT [dbo].[TB_CONFIGURACAO] OFF
SET IDENTITY_INSERT [dbo].[TB_NOTA_COMPRA] ON 

INSERT [dbo].[TB_NOTA_COMPRA] ([ID_NOTA_COMPRA], [DATA_EMISSAO], [VALOR_MERCADORIA], [VALOR_DESCONTO], [VALOR_FRETE], [VALOR_TOTAL], [STATUS]) VALUES (1, CAST(N'2018-02-26 14:31:09.270' AS DateTime), CAST(150.00 AS Numeric(18, 2)), CAST(20.00 AS Numeric(18, 2)), CAST(60.00 AS Numeric(18, 2)), CAST(130.00 AS Numeric(18, 2)), 1)
SET IDENTITY_INSERT [dbo].[TB_NOTA_COMPRA] OFF
SET IDENTITY_INSERT [dbo].[TB_USUARIO] ON 

INSERT [dbo].[TB_USUARIO] ([ID_USUARIO], [LOGIN], [SENHA], [PAPEL], [VALOR_MIN_VISTO_APROVACAO], [VALOR_MAX_VISTO_APROVACAO]) VALUES (1, N'tbda', N'123456', 1, CAST(1000 AS Numeric(18, 0)), CAST(10000 AS Numeric(18, 0)))
SET IDENTITY_INSERT [dbo].[TB_USUARIO] OFF
ALTER TABLE [dbo].[TB_HISTORICO_APROVACAO]  WITH CHECK ADD FOREIGN KEY([ID_NOTA_COMPRA])
REFERENCES [dbo].[TB_NOTA_COMPRA] ([ID_NOTA_COMPRA])
GO
ALTER TABLE [dbo].[TB_HISTORICO_APROVACAO]  WITH CHECK ADD FOREIGN KEY([ID_USUARIO])
REFERENCES [dbo].[TB_USUARIO] ([ID_USUARIO])
GO
